# The URL the site will be built for
base_url = "https://imrangm.github.io"

title = "An eportfolio for Imran Mustafa"
description = "An eportfolio for Imran Mustafa"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# The default language; used in feeds.
default_language = "en"

[extra]
# User settings
username = "Imran Mustafa"
user_description = "I am a Software Developer with expertise in C/C++ and Python."
user_title = "Software Developer"
email = "imranmustafa@acm.org"
twitter_username = "@ImranAE"
github_username =  "Imrangm"

# Google-analytics
google_analytics.id = ""
