name: Deploy Zola site to Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Publish site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: Build and deploy
        uses: shalzz/zola-action@v0.18.0
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}